### ISSUE TITLE
Integrating DataWedge

### ISSUE THREAD

**Issue by dung90it** [darryncampbell/DataWedgeKotlin#3]
how to configure this DataWedge to not stick invoke startActivity() on each scan?, I want to receive scans via Broadcast Receive

**Comment by darryncampbell** [comment]
Hi, you will need to pass in "2" in this line: https://github.com/darryncampbell/DataWedgeKotlin/blob/master/app/src/main/java/com/darryncampbell/datawedgekotlin/MainActivity.kt#L165 (currently "0" is passed in) and also register a filter for your action at https://github.com/darryncampbell/DataWedgeKotlin/blob/master/app/src/main/java/com/darryncampbell/datawedgekotlin/MainActivity.kt#L51.  The action you are registering for should match https://github.com/darryncampbell/DataWedgeKotlin/blob/master/app/src/main/java/com/darryncampbell/datawedgekotlin/MainActivity.kt#L164, i.e. com.darryncampbell.datawedgekotlin.SCAN in the example.  Each scan should then be received in https://github.com/darryncampbell/DataWedgeKotlin/blob/master/app/src/main/java/com/darryncampbell/datawedgekotlin/DWReceiver.kt.

**Comment by dung90it** [comment]
Thank you
