### ISSUE TITLE
How to get raw camera input from DataWedge API ? 

### ISSUE THREAD

**Issue by reha2408** [darryncampbell/DataWedgeKotlin#4]
I have MC930B device and writing an application which needs to have raw camera input like Bitmap etc. How to achive this ?

**Comment by darryncampbell** [comment]
No, unfortunately the raw camera input is not available through DataWedge or EMDK.  There is no API to access this for the barcode Imager..

**Comment by reha2408** [comment]
Thank you Darryn.
